# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0002_sentence_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='positive',
            field=models.BooleanField(default=False),
        ),
    ]
