# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_auto_20160922_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
