# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_publication_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='fulltextviewed',
            field=models.IntegerField(default=0),
        ),
    ]
